name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: true
      base:
        description: 'Name of branch to open PR against (e.g. soroban-wasmi-v0.31.1)'
        required: true

jobs:

  bump-version:
    uses: stellar/actions/.github/workflows/rust-bump-version.yml@main
    with:
      version: ${{ inputs.version }}
      base: ${{ inputs.base }}
